import React from "react";
import Navbar from "./Navbar";
import Footer from "./Footer";
import Head from "next/head";

const Layout = ({ children }) => {
   return (
      <div className='h-full'>
         <Head>
            <title>Kenji Wilkie</title>
            <meta name='description' content='Generated by create next app' />
            <link rel='icon' href='/favicon.ico' />
         </Head>
         <Navbar />
         <main className='main'>{children}</main>
         <footer>
            <Footer />
         </footer>
      </div>
   );
};

export default Layout;
